backend:
  name: github
  repo: "tluccas/vilma-plantas-cms"
  branch: main # Branch onde os commits serão feitos
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: auth

media_folder: "public/images/uploads" # Caminho físico
public_folder: "/images/uploads" # Caminho na URL

collections:
  - name: "products"
    label: "Produtos"
    folder: "content/products" # Onde os JSONs serão salvos
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: "Nome do Produto", name: "name", widget: "string"}
      - {label: "Preço", name: "price", widget: "number", value_type: "float"}
      - {label: "Estoque", name: "stock", widget: "number", default: 1}
      - {label: "Categoria", name: "category", widget: "select", options: ["Interior", "Exterior", "Orquídeas", "Mudas", "Vasos", "Suculentas", "Samambaias", "Rosas"]}
      - {label: "Descrição", name: "description", widget: "markdown"}
      - {label: "Em Destaque?", name: "featured", widget: "boolean", default: false}
      
      - label: "Galeria de Imagens"
        name: "images"
        widget: "list"
        fields:
          - {label: "Imagem", name: "url", widget: "image"}