backend:
  name: git-gateway
  branch: prod/vitrine-1.0 # Branch onde os commits serão feitos

media_folder: "vilma-plantas-frontend/public/images/uploads" # Caminho físico
public_folder: "/images/uploads" # Caminho na URL

collections:
  - name: "products"
    label: "Produtos"
    folder: "vilma-plantas-frontend/src/content/products" # Onde os JSONs serão salvos
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: "Nome do Produto", name: "name", widget: "string"}
      - {label: "Preço", name: "price", widget: "number", value_type: "float"}
      - {label: "Estoque", name: "stock", widget: "number", default: 1}
      - {label: "Categoria", name: "category", widget: "select", options: ["Interior", "Exterior", "Orquídeas", "Mudas", "Vasos"]}
      - {label: "Descrição", name: "description", widget: "markdown"}
      - {label: "Em Destaque?", name: "featured", widget: "boolean", default: false}
      
      - label: "Galeria de Imagens"
        name: "images"
        widget: "list"
        fields:
          - {label: "Imagem", name: "url", widget: "image"}